services:
  backend:
    build:
      context: ./backend
    image: sportmate-backend:latest
    container_name: sm_backend
    
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    image: sportmate-frontend:latest
    container_name: sm_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
  